const assert=require('node:assert/strict');const test=require('node:test');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const ext=path.join(__dirname,'../browser-extension');
const src=n=>fs.readFileSync(path.join(ext,n),'utf8');
function R(l,t,w,h){return{left:l,top:t,width:w,height:h,right:l+w,bottom:t+h}}
function N(o={}){const a={...(o.a||{})};return{tagName:o.tag||'DIV',parentElement:o.p||null,isConnected:true,hidden:false,textContent:o.text||'',currentSrc:o.src||'',src:'',duration:o.d??12,innerHTML:o.html||'',_r:o.r||R(0,0,20,20),_q:o.q||(()=>[]),getBoundingClientRect(){return{...this._r}},getAttribute(k){return a[k]??null},matches(s){return(o.m||[]).some(x=>s.includes(x))||(s.includes('button')&&this.tagName==='BUTTON')||(s.includes('[data-e2e]')&&a['data-e2e'])||(s.includes('aria-haspopup')&&a['aria-haspopup']==='menu')},querySelectorAll(s){return this._q(s)||[]},closest(s){for(let x=this;x;x=x.parentElement)if(x.matches?.(s))return x;return null},addEventListener(){},removeEventListener(){},click(){o.click?.()}}}
function load({host='www.tiktok.com',videos=[],dq,clip=''}={}){let clipboard=clip;const body=N({tag:'BODY',r:R(0,0,1200,1000)}),html=N({tag:'HTML',r:R(0,0,1200,1000)}),listeners=[],document={body,documentElement:html,title:'Feed',querySelectorAll(s){if(s==='video')return videos;return dq?.(s)||[]}};const c=vm.createContext({URL,Set,Map,WeakSet,WeakMap,Number,String,Object,RegExp,Date,Promise,decodeURIComponent,globalThis:null,location:{hostname:host,href:`https://${host}/`},document,innerWidth:1200,innerHeight:900,getComputedStyle(){return{display:'block',visibility:'visible',opacity:'1'}},navigator:{clipboard:{readText:async()=>clipboard}},setTimeout:f=>{f();return 1},clearTimeout(){},chrome:{runtime:{onMessage:{addListener(f){listeners.push(f)}}}}});c.globalThis=c;for(const f of['social-player-resolution-v2.js','social-home-feed-v3-core.js','social-home-feed-v3-facebook.js','social-home-feed-v3-tiktok.js','social-home-feed-resolution-v3.js'])vm.runInContext(src(f),c);return{api:c.ADM_SOCIAL_HOME_FEED_V3,v2:c.ADM_SOCIAL_PLAYER_RESOLVER_V2,c,body,setClip:v=>clipboard=v}}
test('0.3.132 normalizes Facebook feed Watch ids and rejects generic Watch',()=>{const{api}=load({host:'www.facebook.com'});assert.equal(api.facebookInfo('https://www.facebook.com/watch/100043996815564/2816970528630277/').url,'https://www.facebook.com/watch/?v=2816970528630277');assert.equal(api.facebookInfo('https://www.facebook.com/watch/hashtag/cats').url,null)});
test('0.3.132 Facebook searches beyond old 20-level feed container',()=>{const v=N({tag:'VIDEO',r:R(100,220,600,420),src:'blob:https://www.facebook.com/a'}),a=N({tag:'A'});a.href='https://www.facebook.com/watch/100043996815564/2816970528630277/';let x=v;for(let d=0;d<30;d++){const p=N({r:R(70,100,820,650),q:s=>s==='video'?[v]:d>=24&&s.includes('/watch/')?[a]:[]});x.parentElement=p;x=p}const f=load({host:'www.facebook.com',videos:[v]});x.parentElement=f.body;assert.equal(f.api.facebookDom(v).url,'https://www.facebook.com/watch/?v=2816970528630277')});
test('0.3.132 TikTok finds Share in outer action rail and encoded permalink',async()=>{let open=false;const v=N({tag:'VIDEO',r:R(250,80,500,760),src:'blob:https://www.tiktok.com/current'}),b=N({tag:'BUTTON',r:R(780,570,48,48),click:()=>open=true}),icon=N({p:b,r:R(785,575,30,30),a:{'data-e2e':'share-icon'}}),copy=N({tag:'BUTTON',r:R(720,300,170,40),text:'Copy link',a:{'data-e2e':'copy-link','data-url':'https%3A%2F%2Fwww.tiktok.com%2F%40owner%2Fvideo%2F7676540110162136322'}});let x=v;for(let d=0;d<12;d++){const p=N({r:R(180,40,700,820),q:s=>s==='video'?[v]:d>=8&&(s.includes('data-e2e')||s.includes('button'))?[icon]:[]});x.parentElement=p;x=p}const f=load({videos:[v],dq:s=>s.includes('[data-e2e*="share"]')?[icon]:open&&(s.includes('[data-e2e]')||s.includes('button'))?[copy]:[]});x.parentElement=f.body;const r=await f.api.tiktokMenu(v);assert.equal(r.url,'https://www.tiktok.com/@owner/video/7676540110162136322');assert.ok(r.extendedScopeNodes>7)});
test('0.3.132 deep TikTok parser handles nested share query',()=>{const{api}=load();assert.equal(api.deepTikTok('https://www.tiktok.com/share?url=https%3A%2F%2Fwww.tiktok.com%2F%40owner%2Fvideo%2F7676540110162136322'),'https://www.tiktok.com/@owner/video/7676540110162136322')});
test('0.3.132 popup keeps playerId preflight and uses V3',()=>{const p=src('popup-social-player-resolution.js');assert.match(p,/player_id_stale/);assert.match(p,/APOCALIPSE_SCAN/);assert.match(p,/APOCALIPSE_RESOLVE_VISIBLE_SOCIAL_MEDIA_V3/)});
test('0.3.143 manifest loads all Home-feed modules and diagnostics counters exist',()=>{const m=JSON.parse(src('manifest.json')),all=m.content_scripts.flatMap(x=>x.js||[]),diag=src('social-home-feed-v3-facebook.js')+src('social-home-feed-v3-tiktok.js')+src('tiktok-share-menu-v4.js')+src('social-home-feed-resolution-v3.js');assert.equal(m.version,'0.3.143');for(const f of['social-home-feed-v3-core.js','social-home-feed-v3-facebook.js','social-home-feed-v3-tiktok.js','tiktok-share-menu-v4.js','social-home-feed-resolution-v3.js'])assert.ok(all.includes(f));assert.match(diag,/extendedScopeNodes/);assert.match(diag,/geometryMatchedControls/)});

test('0.3.135 popup recovers an already-open Facebook tab after an extension update',()=>{const p=src('popup.js');assert.match(p,/recoverUpdatedTabScripts/);assert.match(p,/target: \{ tabId: tab\.id, allFrames: true \}/);assert.match(p,/popup\.tab_scripts_recovered/);assert.match(p,/\{ scanned, error \} = await scanTopFrame\(tab\.id\)/)});
